sequenceDiagram 

actor SalesManager 
participant NewOrderView 
participant NewOrderViewModel 
participant OrderService 
participant OrderRepository 
participant OrderLineRepository
participant OrderLineService
participant PaymentService
participant PaymentRepository
participant NoteRepository
participant PickUpRepository 
participant Database

SalesManager->>NewOrderView: Enter new order information 
NewOrderView->>NewOrderViewModel: CreateOrderCommand.Execute()
NewOrderViewModel->>OrderService: CreateOrder(order, orderLines, payments) 
OrderService->>PickUpRepository: Insert(order.PickUp) 
PickUpRepository->> Database: EXEC spPickUp_Insert(Date, IsDelivery, Location) 
Database ->> PickUpRepository: return Id 
PickUpRepository->> OrderService: return Id 
OrderService->>NoteRepository: Insert(order.Note) 
NoteRepository->> Database: EXEC spNote_Insert(Content) 
Database ->> NoteRepository: return Id 
NoteRepository->> OrderService: return Id 
OrderService->>OrderRepository: Insert(order) 
OrderRepository->>Database: EXEC spOrder_Insert(Date, Status, CustomerId, PickUpId, NoteId) 
Database-->>OrderRepository: return Id 
OrderRepository->>OrderService: return Id 
loop For each OrderLine 
	OrderService ->> OrderLineService: CreateOrderLine(line)
	OrderLineService ->> OrderLineRepository: Insert(orderLine) 
	OrderLineRepository ->> Database: EXEC spOrderLine_Insert(OrderId, ProductId, LineNumber, ...) 
	Database ->> OrderLineRepository: Confirmation 
	OrderLineRepository ->> OrderLineService: Confirmation 
	OrderLineService ->> OrderService: Confirmation 
end 
loop For each Payment 
	OrderService ->> PaymentService: CreatePayment(payment)
	PaymentService ->> PaymentRepository: Insert(payment) 
	PaymentRepository ->> Database: EXEC spPayment_Insert(Date, Amount, PaymentMethodId, OrderId) 
	Database ->> PaymentRepository: Confirmation 
	PaymentRepository ->> PaymentService: Confirmation
	PaymentService ->> OrderService: Confirmation 
end 

OrderService ->> Database: COMMIT (transaction) 
Database ->> OrderService: Confirmation 
OrderService ->> NewOrderViewModel: return result 
NewOrderViewModel ->> NewOrderView: Update UI with result 
NewOrderView->>SalesManager: Show success/failure message 




