using OrderManagerLibrary.Model.Interfaces;

namespace OrderManagerLibrary.Model.Classes;
/// <summary>
/// Represents a customer with their details.
/// </summary>
public class Customer : ICustomer
{
    public int CustomerId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string PhoneNumber { get; set; }

    /// <summary>
    /// Constructor used when loading an existing customer from the database.
    /// The CustomerId is already known (retrieved from a SELECT query).
    /// </summary>
    public Customer(int personId, string firstName, string lastName, string phoneNumber)
    {
        CustomerId = personId;
        FirstName = firstName;
        LastName = lastName;
        PhoneNumber = phoneNumber;
    }
    /// <summary>
    /// Constructor used when creating a new customer before it is saved to the database.
    /// CustomerId is not assigned yet (will be generated by the database).
    /// </summary>
    public Customer(string firstName, string lastName, string phoneNumber)
    {
        FirstName = firstName;
        LastName = lastName;
        PhoneNumber = phoneNumber;
    }
}
